name: tests

on:
  push:
    branches:
      - main
    pull_request:
    schedule:
      - cron: '0 0 * * *'

permissions:
  contents: read

jobs: 
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 18.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Execute tests
        run: yarn ci:test
